### PR TITLE
Minor Data Entry issues in Release 2.0 will jump to 2.1

### PR DESCRIPTION
**Pull request by marcosb1**
Code successfully runs in Postgres lets get this going

### CODE REVIEW

**Comment by blackjack26** [comment]
Is it possible to also fix the issue with inserting a phone number for `agencyMemberInsert()`? It currently has the phone as an `INT` and not `TEXT`. Should be pretty quick.

**Review by Dr-Crow — APPROVED** [review]
Good work on setval!

**Review by Vesiix — APPROVED** [review]

**Review by michelleburd — APPROVED** [review]

**Comment by Dr-Crow** [comment]
Fix the issue Jack raised.

**Review by blackjack26 — APPROVED** [review]

**Review by CBadame — APPROVED** [review]
I must've missed the static value for the employee insert when updating the DF info. Thanks for fixing that!

**Pull request merged**
