### PR TITLE
documentation

### PR DESCRIPTION
**Pull request by Scott123180**
useful documentation for connecting to the database via php

### CODE REVIEW

**Comment by Dr-Crow** [comment]
I do not think any PHP should be in this repo. Talk to the UI team, @blackjack26 , they might have a better place for it.  Additionally, put the images in a PDF with written documentation on what each image is showing.  Right now, its just random images.  @marcosb1 what do you think about the PHP?

**Comment by blackjack26** [comment]
I agree that the PHP probably shouldn't go in this repository. The newest PHP code we have on the WebApp has a [`Database.php`](https://github.com/Capping-CPCA/Web-App/blob/develop/core/database/Database.php) object that is used throughout the whole application. In our `bootstrap.php` file the database connection is initialized and used throughout the application. 

Unless people are going to develop other PHP code that is not the main web application, I don't think there is a need to show how to connect to the database through PHP.

**Comment by Scott123180** [comment]
Sounds like a plan. I didn't realize the branch name change from UI-design to web-app. I'm guessing that means that your team @blackjack26  is going to be doing the whole wep-side of the application. Our requirements changed to where there needs to be a PHP attendance sheet up and running for simplicity first. I'll shoot Algozine an email and see what's up and also ask him in class.

As for the separation of php, I can remove the php part and just leave the part of how to connect to the DB with PHPStorm instead of PGAdmin, so it's all DB related.

@Dr-Crow are the images not displaying correctly? The way it's marked up it should show as bullet point, then image right below

**Comment by Dr-Crow** [comment]
Oh, I see it now @Scott123180 . Was not click the right button. I get what you are trying to do.  Instead of doing this, please add to our wiki. @marcosb1 already started a section for connection info. Feel free to add on to it. 

https://github.com/Capping-CPCA/Database/wiki/Connection-Guide

**Pull request closed without merging**
