### PR TITLE
Survey update

### PR DESCRIPTION
**Pull request by CBadame**
Made some changes to TABLES.sql and PROCEDURES.sql for the survey's team. I've tested everything with them on the db in the survey-update branch, and everything is in working order...just want to make sure this won't break anything else.

### CODE REVIEW

**Review by marcosb1 — COMMENTED** [review]
@Dr-Crow did we want Surveys to decide the creation of `ClassOffering`?

**Comment by CBadame** [comment]
@marcosb1 The surveys do not keep track of curriculum, so they are unable to create a new class offering

**Comment by marcosb1** [comment]
I know, but @Dr-Crow I think wanted it to work this way...

**Comment by Dr-Crow** [comment]
@CBadame when you take the survey it records the curriculum and class info. Thus allowing them the ability to create a class offering if on is not there already. Or that is how it should work.

**Comment by CBadame** [comment]
I'm not sure it can though. They don't have any data in their survey that can link a form to a specific curriculum, and that's not something a participant would be able to provide. The only way I could think of accomplishing it would possibly be to have the logged in employee provide this info before uploading the survey results?

**Comment by CBadame** [comment]
@Dr-Crow The survey team told me exactly what data they're keeping track of, and were adamant about the fact that curriculum is not a part of that list.

**Comment by marcosb1** [comment]
@CBadame @Dr-Crow why can't they just provide the curriculum when the survey is made ?

**Comment by CBadame** [comment]
@marcosb1 you mean the facilitator/employee? Cause I could ask them to update their tab on the UI to allow for that

**Comment by marcosb1** [comment]
@CBadame As in, when the survey gets created, can't they just ask the facilitator to say which classID and curriculumID its for?

**Comment by CBadame** [comment]
I don't see why not. I'll ask Roman and Ryan and see what they say. Do we want them to have to know the id's off-hand though? Or should we just allow them to choose a curriculum name and class name?

**Comment by Dr-Crow** [comment]
@CBadame When I talked to them last with Algozzine and everyone else in the conference room they agreed they needed to provide some info to generate a class offering.  But now with changes to class offering maybe we can change how it functions. To generate the basic class offering they only need the sitename and date(TIMESTAMP). Maybe have them just generate that. Once the attendance it actually sync have them input the FKs of curriculimID and classID? @marcosb1 do you think that would work?

**Review by marcosb1 — COMMENTED** [review]
is that `PHP` on line `655` of `PROCEDURES.sql`? @CBadame (nevermind)

**Review by marcosb1 — APPROVED** [review]
Looks good to me.

**Review by Dr-Crow — APPROVED** [review]

**Review by jrands — APPROVED** [review]

**Pull request merged**
